### PR TITLE
style(docs): added badges to README + doc link

### PR DESCRIPTION
**Pull request by MichaelHirn**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 1399303fc4d70c2752e74dbeb8cfbc4a51811245
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**
- Commit: 593dcffb0e332d6c990d4bc06483925c6b84ac17
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**
- Commit: 7bf961dee72f7535f7409586d2cd7a7c212f9e5a
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/storeness/cuticula

---

This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 593dcffb0e332d6c990d4bc06483925c6b84ac17
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**
- Commit: 7bf961dee72f7535f7409586d2cd7a7c212f9e5a
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/storeness/cuticula

---

This message was auto-generated by https://gitcop.com

**Comment by MichaelHirn** [comment]
@homu +r

**Comment by MichaelHirn** [comment]
@homu r+

**Pull request merged**
